### ISSUE TITLE
PPS train returned with non-zero status

### ISSUE THREAD

**Issue by driscolc** [algbioi/ppsp#2]
Hi, 

I'm getting an error with PPSP that says this: 

```
PPS "train" return code: 1
Traceback (most recent call last):
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 1008, in <module>
    main()
  File "/apps/pps/tools/ppsplus/algbioi/core/run.py", line 510, in main
    raise Exception("PPS train returned with non-zero %s status: %s" % (trainProc.returncode,     trainCmd))
Exception: PPS train returned with non-zero 1 status
```

I've checked the PPS train log, and it looks like this: 

```
/apps/pps/tools/PhyloPythiaS/1_3/scripts/train.rb:603: warning: shadowing outer local variable - c_val
/apps/pps/tools/PhyloPythiaS/1_3/scripts/train.rb:607: warning: shadowing outer local variable - cv_out
/apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/utils.rb:92: warning: method redefined; discarding old count
/apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/sqlite_utils.rb:265: warning: assigned but unused variable - rank_cache
/apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/tree.rb:594: warning: assigned but unused variable - step
/apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/tree.rb:706: warning: assigned but unused variable - distance
/apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/pathway.rb:594: warning: assigned but unused variable - i
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36: warning: loading in progress, circular require considered harmful - /apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/tree.rb
    from /apps/pps/tools/PhyloPythiaS/1_3/scripts/train.rb:17:in `<main>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/sqlite_utils.rb:25:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/tree.rb:851:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /apps/pps/tools/PhyloPythiaS/1_3/scripts/lib/rubygems/bioruby/lib/bio/db/newick.rb:22:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
Processing according to   /media/data/Connor/PacBio/mmgenome_PBreads/mmgenome_PBreads/ppsp_AFA_cul_corrected/wo rking/PPS_config_generated.txt (2016-01-13 03:45:11 -0800)
Unknown configuration file option: N_CLASSIFIERS...ignoring
Unknown configuration file option: PIE_CHARTS...ignoring
Processing NCBI data... done
Generating tree from the clades list (24 clades)... sh: 1:     /apps/pps/tools/PhyloPythiaS/1_3/scripts/ncbi2newick.rb: not found
/apps/pps/tools/PhyloPythiaS/1_3/scripts/train.rb:294:in `<main>':  (RuntimeError)
Tree creation from nodes list failed!
```

So I'm guessing the problem is that PPS train is not finding the ncbi2newick.rb script in the location stated. However, I've checked and it's in the right place, with appropriate permissions to run.

**Comment by algbioi** [comment]
Hi, this looks like a corrupted installation, are you using the virtual machine installation and installed/updated the tools and the reference?

**Comment by driscolc** [comment]
I actually used the Ubuntu installation, since that's what our machine runs and we'd like to be able to run ppsp remotely. The tools and reference have been updated, and I re-ran the test and received the same error.
