### ISSUE TITLE
cannot install NCBI database

### ISSUE THREAD

**Issue by itiago** [algbioi/ppsp#7]
Hi
I have always this error when trying to install NCBI database.
I'm trying to use this oracle VM image.
I run the commands:
wget https://raw.githubusercontent.com/algbioi/ppsplus/master/algbioi/ref/update.py -O /apps/pps/sys/update.py
then
update ‐s
update -t
then tried to use the update -r NCBI20121122
with no success
can you help me?
Thank you

user1@vm:~$ update -r NCBI20121122
Data preparation started!
Downloading file: https://research.bifo.helmholtz-hzi.de/software/ppsp/1_4/reference_NCBI20121122.tar.xz 
File size: 4449.0 MB
Progress:

Can't determine local destination for file: /mnt/host_shared/reference_NCBI20121122.tar.xz
Traceback (most recent call last):
  File "/apps/pps/sys/update.py", line 335, in <module>
    _main()
  File "/apps/pps/sys/update.py", line 315, in _main
    updateData(settings, type='ref')
  File "/apps/pps/sys/update.py", line 263, in updateData
    downloadFile(fileName, settings, type)
  File "/apps/pps/sys/update.py", line 128, in downloadFile
    raise e
IOError: [Errno 13] Permission denied: '/mnt/host_shared/reference_NCBI20121122.tar.xz'
user1@vm:~$

**Comment by algbioi** [comment]
Please make sure that the mounted file system if mounted correctly and that you have the right to write to it.
